server:
  port: 9090
book:
  url: http://b5jz3k.natappfree.cc

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: 123456
    password: root
    url: jdbc:mysql://localhost:3306/aaa?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai

mybatis-plus:
  global-config:
    db-config:
      # 逻辑删除字段`status`
      logic-delete-field: status
      # 删除时，status的值
      logic-delete-value: 0
      # 未删除时，status的值
      logic-not-delete-value: 1